spring.application.name=tareaBackend

spring.datasource.url = jdbc:mysql://localhost/kotlinrest?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=true
#spring.datasource.url=jdbc:mysql://localhost:3306/kotlinrest?serverTimezone=Europe/Madrid&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform = org.hibernate.dialect.MySQL57Dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.username = usuario
spring.datasource.password = 1224

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Valores: none, validate, update, create, create-drop <= default
#spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.hibernate.ddl-auto=update
# Deshabilita la AutoconfiguraciÃ³n de Spring Security
# Esto resuelve el error 403 Forbidden para las peticiones GET, POST y DELETE.
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# Puerto típico
server.port=8080

# Clave secreta para firmar tokens (mín 32 caracteres) Contraseña interna del servidor para firmar lso tokens
security.jwt.secret=TacwPiifpAyTQAZHmhq7mHFigrFzGbwq

# Duración del token (minutos)
security.jwt.expiration-minutes=60